<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete selected items?' => 'Tem certeza que deseja excluir os itens selecionados?',
    'Are you sure you want to delete this item?' => 'Tem certeza que deseja excluir este item?',
    'Cancel' => 'Cancelar',
    'Create' => 'Criar',
    'Delete' => 'Excluir',
    'Delete selected' => 'Excluir selecionado',
    'You need to select at least one item.' => 'Voc6e precisa selecionar pelo menos um item.',
];
